# action.yml
name: action
description: 'Simple action demo'

inputs:
  file:
    description: 'File path'
    required: true
  required:
    description: 'Whether or not it is required'
    required: false

runs:
  using: docker
  image: docker://ghcr.io/mchmarny/action:v0.0.11
  args:
    - print
    - --file
    - ${{ inputs.file }}
    - --required
    - ${{ inputs.required }}

branding:
  icon: arrow-up
  color: gray-dark
