name: valid

on:
  workflow_call:
    inputs:
      file:
        description: 'File path'
        required: true
        type: string
      required:
        description: 'Whether or not it is required'
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  import:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      packages: read
    steps:

    - uses: mchmarny/action@main  # pinned to digest in real use
      with:
        file: ${{ inputs.file }}
        required: ${{ inputs.required }}