name: valid

on:
  workflow_call:
    inputs:
      file:
        description: 'File path'
        required: true
        type: string
      required:
        description: 'Whether or not it is required'
        type: boolean
        default: false
    outputs:
      output:
        value: ${{ jobs.validation.outputs.output }}
      processed_on:
        value: ${{ jobs.validation.outputs.processed_on }}

permissions:
  contents: read

jobs:
  import:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      packages: read
    outputs:
      output: ${{ steps.validation.outputs.output }}
      processed_on: ${{ steps.validation.outputs.processed_on }}
    steps:

    - id: validation
      uses: mchmarny/action@main  # pinned to digest in real use
      with:
        file: ${{ inputs.file }}
        required: ${{ inputs.required }}